In [1]:
import numpy as np

In [2]:
m= np.array([[1,-1,1],
             [3,2,0]])

In [3]:
print(m)

[[ 1 -1  1]
 [ 3  2  0]]


In [6]:
m1=np.array([[1],[2],[3]])

In [7]:
print(m1)

[[1]
 [2]
 [3]]


In [10]:
#Matriz traspuesta
#Se obtene cambiando sus filas por columnas (o viceversa)

print(np.transpose(m1))

[[1 2 3]]


In [15]:
#sistemas de Ecuaciones 

A = np.array([[2,1,-1],
              [3,0,1],
              [1,1,-1]])

In [16]:
print(A)

[[ 2  1 -1]
 [ 3  0  1]
 [ 1  1 -1]]


In [18]:
b = np.array([[-3],[5],[-2]])

In [21]:
print(np.transpose(b))

[[-3  5 -2]]


In [23]:
x= np.linalg.solve(A,b)
print(x)

[[-1.]
 [ 7.]
 [ 8.]]


In [24]:
#comprobacion

print(np.allclose(np.dot(A,x),b))

True


In [26]:
#2x + 7y + 3z = 1
#2x + 8y + 2z = 1
# x + 3y +  z = 0


m1 = np.array([[2, 7, 3],
               [2 ,8, 2],
               [1, 3, 1]])

print(m1)

[[2 7 3]
 [2 8 2]
 [1 3 1]]


In [29]:
m2 = np.array([1,1,0])
m2.shape=(3,1)
print(m2)

[[1]
 [1]
 [0]]


In [30]:
print(np.linalg.solve(m1,m2))

[[-2. ]
 [ 0.5]
 [ 0.5]]


In [ ]:
#comprobacion
