In [2]:
import numpy as np

In [3]:
m = np.array([[0,1,2],
              [4,2,3]])

In [4]:
print(m)

[[0 1 2]
 [4 2 3]]


In [5]:
print(np.sum(m, axis=0))

[4 3 5]


In [6]:
print(np.sum(m, axis=1))

[3 9]


In [7]:
m1 = np.array([[1,1],
              [1,1]])

m2 = np.array([[8,8],
               [8,8]])


In [14]:
print(m1)
print("")
print(m2)

[[1 1]
 [1 1]]

[[8 8]
 [8 8]]


In [15]:
#Funcion para concatenar o unir
print(np.concatenate([m1,m2], axis=0))

[[1 1]
 [1 1]
 [8 8]
 [8 8]]


In [16]:
#Funcion para concatenar o unir
print(np.concatenate([m1,m2], axis=1))

[[1 1 8 8]
 [1 1 8 8]]


In [17]:
m1 = np.array([1,1])

m2 = np.array([8,8])

In [18]:
print(m1)

[1 1]


In [19]:
print(m2)

[8 8]


In [23]:
print(np.concatenate([m1,m2],axis=0))

[1 1 8 8]
