In [1]:
import numpy as np

In [3]:
m = np.array([(1,2,3,4,),(1,2,3,4)])

In [4]:
print(m)

[[1 2 3 4]
 [1 2 3 4]]


In [6]:
print(np.ndim(m))

2


In [8]:
print(np.alen(m))

2


In [10]:
print(m.dtype)

int64


In [13]:
a = np.array([15,20,25])
b = np.array([[15,20,25]])

print( np.array_equal(a,b))

False


In [14]:
print(a)

[15 20 25]


In [15]:
print(b)

[[15 20 25]]


In [19]:
a2 = np.array([[10,18],
               [12,14],
               [11,15]])


a2.shape

(3, 2)

In [22]:
c = np.array([10,18,9,11,13,15])
print(c.reshape(4,2))

ValueError: cannot reshape array of size 6 into shape (4,2)

In [32]:
d = np.array([[3,2,9,5],[2,4,1,8],[4,5,6,3]])
print(d)
print(d[1,2])

[[3 2 9 5]
 [2 4 1 8]
 [4 5 6 3]]
1


In [39]:
f = np.array([[1,3,5],
             [50,100,150],
             [2,4,6]])
print(f)

print(f[1,0:3])

[[  1   3   5]
 [ 50 100 150]
 [  2   4   6]]
[ 50 100 150]


In [59]:
g =  np.array([[1, 0, 0],
                [0, 1, 0],
                [0, 0, 1]])

print(g)

print(g[0:3,2])

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[0 0 1]
