In [1]:
import numpy as np

In [5]:
m = np.arange(20).reshape(4,5)
print(m.shape)
print(m)

(4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
print(m.ndim)

2


In [7]:
print(m.size)

20


In [8]:
m2 = np.zeros((3,4))
print(m2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#linespace(a,b,c)  a primer valor, b ultimo valor , c numero de elementos
m3 = np.linspace(99,88,25)
print(m3.size)
print(m3)


25
[99.         98.54166667 98.08333333 97.625      97.16666667 96.70833333
 96.25       95.79166667 95.33333333 94.875      94.41666667 93.95833333
 93.5        93.04166667 92.58333333 92.125      91.66666667 91.20833333
 90.75       90.29166667 89.83333333 89.375      88.91666667 88.45833333
 88.        ]


In [11]:


m4 = np.arange(24).reshape(2,3,4)
print(m4.size)
print(m4)

24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
#Matriz de tres dimenciones 
m5 = np.arange(27).reshape(3,3,3)
print(m5.size)
print(m5)

27
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
