In [25]:
import numpy as np

In [26]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [27]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#numero MAximo
print(np.amax(m))

9


In [29]:
#valor minimo
print(np.amin(m))

1


In [30]:
#axis1
print(np.amax(m,1))

[3 6 9]


In [31]:
#axis 0
print(np.amax(m,0))

[7 8 9]


In [32]:
#rango maximo y minimo

print(np.ptp(m))

8


In [33]:
#rango maximo y minimo

#axis1
print(np.ptp(m,1))

[2 2 2]


In [34]:
#Perceptiles
#perceptiles = q(n+1)/100  --> cuando es impar el numero de elementos 
#q = perceptil a calcular (0-100)
#n = total de datos


#si es par 
# (q * n) / 100
#50  = q
print(np.percentile(m,50))




5.0


In [35]:
print(np.percentile(m,50,axis=1))

[2. 5. 8.]


In [36]:
#Mediana  
#mesiana = (n+1)/2

print(np.median(m))

5.0


In [37]:
print(np.median(m, axis=0))

[4. 5. 6.]


In [38]:
print(np.median(1))

1.0


image.png

In [39]:
#Media Aritmetica
# media aritmetica = x1 + x2 ... + xn / n

print(np.mean(m))

5.0


In [40]:
m = np.array([1,2,3,4,5,6])

In [41]:
#promedio ponderado
#x1*p1+  xn*pn /sum p

print(m)


[1 2 3 4 5 6]


In [42]:
print(np.average(m))

3.5


In [43]:
#Desviacion estandar 

#Desviacion estandar = raizcuadrada(sum | x - xal2/n )
#std= sqrt(mean(abs(x-x.mean())**2))

print(np.std(m))

1.707825127659933
