In [1]:
import numpy as np

In [2]:
m2d = np.array([[1,2,3],[4,5,6]])

In [3]:
print(m2d)

[[1 2 3]
 [4 5 6]]


b

In [9]:
lista = [[1,2,3,4,5]]
matriza= np.array(list)
print(matriza)

<class 'list'>


In [7]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]
matriz2=np.array(lista2)
print(matriz2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


auto matriz

In [10]:
m=np.arange(20).reshape(4,5)
print(m)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
