In [1]:
import numpy as np

In [6]:
#Que no se pueda predecir logicamente

m = np.random.randint(10, size=5)
print(m)

[2 4 5 4 2]


In [7]:
m = np.random.randint(10, size=(3,3))
print(m)

[[5 6 4]
 [7 5 4]
 [0 9 7]]


In [11]:



m1 = np.random.rand(2,2)
print(m1)

[[0.36503915 0.31428485]
 [0.93182615 0.89350145]]


In [13]:
m1 = np.random.choice([3,4,8,7,9,1])
print(m1)

8


In [14]:
m1 = np.random.choice([3,4,8,7,9,1], size=(2,3))
print(m1)

[[7 3 1]
 [9 7 4]]


Distribucion Aleatoria

Es una lista de todos los valores posibles y la frecuencia con la que se produce cada valor

Es un conjunto de nuemros aleatorios que siguen una determinada funcion de densidad de probabilidad


In [69]:
#dados
m = np.random.choice([2,4,6],p = [0.5,0.3,0.2], size=(6))
print(m)

[4 2 4 6 2 2]


In [74]:
#Genere una matriz que contenga 50 valores, donde cada valor  debe de se 4, 2, 8 o 10
m = np.random.choice([2,4,8,10],p = [0.3,0.3,0.2,0.2], size=(50))
print(m)



[ 2  2  2  8  2  4 10  4  8 10  4 10  8  2 10  4 10  8  2  2  4 10  4  4
  2  2  8  8  2  2 10  8  2  4  4  2 10 10 10  4  4  8  8  2  4  8  2  4
  4  4]
