In [2]:
import numpy as np

In [3]:
m = np.arange(24).reshape(4,6)
print(m[3,4])
print(m)

22
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
#ordenar los elementos
m1 = np.array([90,7,9,4,2,1])
print(np.sort(m1))

[ 1  2  4  7  9 90]


In [5]:
#power elevar a una potencia
m2 = np.array([2,3])
print(np.power(m2,3))

[ 8 27]


In [8]:
m3 = np.array([2,3])
print(np.array(m3**2))

[ 4  9 64 81 36]


In [9]:
#clasificación
m4 = np.array([2,3,4,5,6,7])
print(np.array(m4 >= 4))

[False False  True  True  True  True]


In [11]:
m5 = np.array([2,3,4,5,6,7])
print(np.array(m5.max()))
print(np.array(m5.min()))

7
2


In [13]:
m6 = np.array([2,3,4,5,6,7])
m7 = np.array([12,13,14,15])
print(np.concatenate((m6,m7)))


[ 2  3  4  5  6  7 12 13 14 15]


In [16]:
m8 =np.array([[1,2],[3,4]])
m9 =np.array([[5,6],[7,8]])

print(m8+m9)

[[ 6  8]
 [10 12]]


In [17]:
#sumando 2 a la m10
m10 =np.array([[1,2],
               [3,4]])

m11 =np.array([[5,6],
               [7,8]])

print(m10 + 2)

[[3 4]
 [5 6]]


In [20]:
print(np.add(m10,m11))


[[ 6  8]
 [10 12]]


In [21]:
print(np.subtract(m10,m11))

[[-4 -4]
 [-4 -4]]


In [22]:
print(np.multiply(m10,m11))

[[ 5 12]
 [21 32]]


In [23]:
print(np.divide(m10,m11))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
m10 =np.array([[1,2],
               [3,4]])

m11 =np.array([[5,6],
               [7,8]])
print(m10.dot(m11))

[[19 22]
 [43 50]]
